### ISSUE TITLE
random reading on hbg/bow/lbg wp_dat_g

### ISSUE THREAD

**Issue by agungarifr** [fre-sch/mhw_armor_edit#1]
hello i happen to check your app, i found something unussual, i tried open the chunk folder using the menu on the top left, then i opened bow.wp_dat_g but it shown uncomplete list off data and at the desc column it says lbgnumbers, tried the other wp_dat_g files the reading keep showing lbg data, which is weird.

i tried to get new chunk file, then redo it, but its still giving the same lbg data on hbg/bow.wp_dat_g

**Comment by fre-sch** [comment]
Thanks for reporting that.
It was always only using the lbg translation file, regardless of the actual wp_dat_g opened. I've quickfixed this in 30c7f9ec885a42d05d12b0a2f2820ab96da7b9d4, but still have to create a new release.

**Comment by fre-sch** [comment]
Should be fixed with v1.1.0, closing this for now.
