### ISSUE TITLE
Update for mhw iceborne

### ISSUE THREAD

**Issue by RamenNoodles** [fre-sch/mhw_armor_edit#12]
Will there be an update for iceborne?

I get a magic byte error when trying to edit new files.

**Comment by potter420** [comment]
> Will there be an update for iceborne?
> 
> I get a magic byte error when trying to edit new files.

Hi, I figure out some fixes for certain file, we can fork then continue to work.

Do you have any coding expertise?

**Comment by RamenNoodles** [comment]
> Hi, I figure out some fixes for certain file, we can fork then continue to work.
> 
> Do you have any coding expertise?

I have some, but not with python.
