### ISSUE TITLE
Issue with loading *.wp_dat files

### ISSUE THREAD

**Issue by quanvinh** [fre-sch/mhw_armor_edit#15]
![error](https://user-images.githubusercontent.com/12446721/73199938-6a0f1900-4168-11ea-9dfc-f101d50baf4f.PNG)

.wp_dat_g and other files are opened just fine.

**Comment by fre-sch** [comment]
Based on the error the editor is failing on loading the file `common\equip\kireaji.kire`. The magic byte mismatch looks like you might have an old version (pre iceborne) of `common\equip\kireaji.kire`. Can you try to re-extract a current unmodded version of that file and see if you still get that error?

**Comment by quanvinh** [comment]
I figured out what was wrong. Apparently not only the chunk directory has to be correct (pointing to new Iceborn's chunk), the mod directory has to point to a blank / directory that doesn't contain any old moddes files too. My mod directory was pointing to the old MHW Editor Suite's mod folder, hence the error.

Thanks for the help!
