### ISSUE TITLE
Loading .skl_dat files does not work

### ISSUE THREAD

**Issue by Fexty12573** [fre-sch/mhw_armor_edit#16]
Trying to open a .skl_dat file gives me ![this error.](https://user-images.githubusercontent.com/60443001/73381937-e750a000-42c6-11ea-94e6-8092616a553c.jpg)

**Comment by Asatoshi314** [comment]
I have the same issue

**Comment by foxkitsune006** [comment]
Same here.

**Comment by fre-sch** [comment]
[Very basic support for editing added.](https://github.com/fre-sch/mhw_armor_edit/releases/tag/v1.8.1-alpha)

The main issue with the skl_dat are that the params' effect varies by skill. For example the attack skill, param7 is affinity bonus, and param8 is attack bonus, where as for the health skill, param7 is the elemental bonus and param8 is the health bonus. I don't know the actual details however, and I'm also not motivated to investigate.
If somebody investigates and shares this information, I'll gladly implement a better editor.

**Comment by quanvinh** [comment]
> 
> 
> If somebody investigates and shares this information, I'll gladly implement a better editor.

Hello, guess I can help with this. However, could you tell me where to get the first column in skl_dat file? I can get the skill name from skl_pt_dat but not this column. It wouldn't show up when I export to CSV either.

![image](https://user-images.githubusercontent.com/12446721/73720163-e949b180-4753-11ea-8486-5a130f0d062e.png)

**Comment by foxkitsune006** [comment]
It's fine to just leave it as param1 2 3 etc. we'll figure out what's what. it's not hard to do anyway. some are just boolean whether the skill's active or not, and some have multiple values for multiple stuff in one skill. It's understandable if it's hard to do, so yeah. the editor's good enough I'd say. or rather, I'd appreciate it more if you work expanding the editor to other file extensions now. great job mate.

**Comment by fre-sch** [comment]
@quanvinh I've added copy to clipboard for 1.9.0, now you can select and copy that table: 

- open skl_dat
- click a cell
- ctrl-a to select all
- ctrl-c to copy, or use right-click menu "Copy"
- the data is copied as TAB separated text, so you can just paste this into a spreadsheet like excel

I would need for a better skl_dat editor for each param (now 1-12):

- name of param effect (attack bonus, affinity bonus, cooldown time, or just "unused")
- min value
- max value (or max safe value before game crashes)
