### ISSUE TITLE
Armor crafting menu crash

### ISSUE THREAD

**Issue by eternallydissolved** [fre-sch/mhw_armor_edit#3]
Upon using the 1.01 alpha release and in this subsequent release i am running into a crash whenever i go to craft new armor in the game while using armor files edited with the editing suite. Additionally it will also crash when swapping decorations or in the change equipment screen or crafting weapons ect, if i am in the menu too long; roughly long enough to swap a few decorations. This is repeatable and appears to stem from some form of corruption in the armor file. It is more pronounced when trying to load the armor creation menu as the menu does not come up at all; the preview window starts to come up, and it insta-crashes.

**Comment by fre-sch** [comment]
Can you describe what kind of edits you made to the armors?

If you can, try and narrow it down, to one armor part and/or one specific edit that causes the crashes?

**Comment by agungarifr** [comment]
the only crash i've seen by using edited armor/weap is on multiplayer only.
is there a way to avoid this crash on multiplayer? i have no idea what caused it, perhaps more than 1 person using edited equips in the party? or even the edited shell table might caused it

**Comment by eternallydissolved** [comment]
I play only in single private online session. the first release did not cause this so i think that it may be related to the editor pulling the crafting requirements files. i will create a dummy armor edit file with one, or 2 small edits and test.

**Comment by eternallydissolved** [comment]
Thus far in my dummy file, i edited only the leather headgear, which worked fine. 
then i edited the leather head gear and mail without saving after editing each piece(saving after i had finished the test edit) and the error was introduced into the new armor file. 
I think i have figured it out. when you edit a piece of armor for skills, or set bonuses, if you are not saving after each individual piece, the skills overlap to both pieces and are causing corruption.  for this test i edited the low rank leather set editing the headgear to 100 defense and saved, which works as intended. 
i then edited the leather mail, then the leather gloves to 100 defense and saved which also worked as intended. I then edited just the set bonuses on the leather head gear to razor sharp/spareshot(162) at level 3, and guts(160) at level 3 and saved;this also works as normal. here is where it is getting dicey,
i edited the leather mail to soul of the dragon(164) at level 4 and hero's protection(148) at level 1 and the leather gloves to odogaron mastery(154) at level 4 and legiana favor(152) at level 4, then saved after editing those 2. I can load into the armor forging menu at this point still, but on the low rank leather set, the skills are screwed up. It is displaying half of the soul of the dragon skill without the name, only the icon and the number 4 next to it, razor sharp, guts and hero's protection show as normal and the 2 skills i put on the leather gloves do not show at all, although when looking at just the gloves, it shows the odogaron one. this is in viewing the skills for the whole set. It does not appear to be tied to any specific skill, but rather how the data is stored in ram if you work on multiple set pieces before saving. I am going to rebuild my entire armor file saving after each piece and report back if it works normally

**Comment by eternallydissolved** [comment]
Through attempting to rebuild my armor file, i decided to just do the leather set first, saving after each piece, and just that set, i got the instant crash. I have noticed however that upon your first save, you have to reopen all armor set drop downs on the left side of the editor, which will then once again reveal each individual piece to edit, and upon subsequent saves, it isn't necessary. It may be that after saving, you need to reopen the armor set to avoid corruption, or you may need to do all of your edits in 1 shot. I will test and report back.

**Comment by eternallydissolved** [comment]
For now, making all of my edits in one go without saving between set pieces allows me to create a functional armor file without the error. i will test in a little bit as to if i can edit that file with the editor without creating a corrupted file as i have backed my new working one up.

**Comment by fre-sch** [comment]
@agungarifr I recommend you only play private sessions when using mods. Modded clients can indeed cause crashes for unmodded clients when playing online. That's out-of-scope for my editor however.

@eternallydissolved Thanks for taking the time and your effort investigating this.

Aside from possible editor issues:
Last I checked, the game cannot handle more than 5 distinct Set Bonus skills, without eventually freezing/crashing. To be specific: you can mod an armor set to have 5 distinct set bonus skills, equip that, and play with it. But as soon as the game needs to display a sixth set bonus skill anytime in the UI, ie while browsing/swapping armors, the game will freeze/crash. It also cannot handle more than 3 distinct skills per armor piece, that's a crash when going to the smithy.

The editor doesn't enforce this kind of consistency (yet).

**Comment by eternallydissolved** [comment]
Unfortunately, that is not what is creating the issue as i made it a point to just edit 2 armor pieces in one of my tests, and 1 set skill per piece, and still the same thing. Here is a test i would like you to attempt, if you are so inclined, use your editor to mod the armor file, then from there, save it and mod another few pieces making sure to change some skills, but stay in the confines of the limitations you mentioned to me; save it again then load the game and try to craft some armor pieces. In my experience, it has crashed. I also have no problem switching between armor pieces even on the corrupted files unless i am in the menus for a while, then it will crash. additionally in my own testing, there is an over all effect limit of 32, but skills like lunastra favor and odogaron mastery do count as 1 skill. i have 35 listed in my current skills load out, but 32 overall and as the guy who data mapped the skills file itself for the fearlessrevolution game hacking forum, i can confirm this without a shadow of a doubt. I can edit the skills themselves via hex editor, and for your editor suite, i am going to share that data with you, although some skills like evade window do pull from another file and cannot be altered(iframes in this case) to be more effective from the skills data file. I am sure that there is an overall limit to how many set skills can be parsed at a time, on all of the sets in my old armor file, i never ran more than 5 total, and that is including running the guard up skill decoration in my set accounting for the fifth(uragaan protection or guard up for the skill decoration)skill. There is still some data in each skill entry that i have no idea what does at this time and changing that does nothing so i  believe they may be place holders for changes to the skills to come in the future. I have also figured out the file that defines sharpness values for weapons as i have edited those as well. Those levels are defined by a numeric value of 1-118 decimal, with each number corresponding to a completely different sharpness gauge, and then there is a 1-8 level which denotes how much of that number actually fills the gauge you see when viewing a weapons properties, and how much of the gauge you see. i can also confirm that there is a place holder for purple sharpness in that data file. To assist in improving your phenomenal editor, i will share both of these with you. This is really a great job for an beta release and considering it is still in alpha; bravo. I just wish to help where i am able.

**Comment by agungarifr** [comment]
@fre-sch ok noted, aside from armor & weapon mods, minor mods works fine on multiplayer, i wont mention specifically, to avoid abuse from another player lol

**Comment by fre-sch** [comment]
Since the editor can't possibly know what pieces will be equipped together, and at best can only validate per piece, I'm closing this. See #6
