### ISSUE TITLE
what means "missing t9n" ?

### ISSUE THREAD

**Issue by soulkee** [fre-sch/mhw_armor_edit#4]
i used 1.2.0 alpha, and When I opened the Armor file, the word 'Missing t9n' was printed next to the armor series name. In addition, all items are left blank and click to cause a crash. I think this problem is related to language but I am not a programmer but I do not know in detail.
Just in case I am using Korean.

**Comment by cnrat** [comment]
You have to let the chunk folder like this below:
\common\equip
\common\text\steam
'missing t9n' means the program can not find language file under \common\text\steam.
You can get all language file extract from \chunk\chunk0.bin

**Comment by cnrat** [comment]
> You have to let the chunk folder like this below:
> \common\equip
> \common\text\steam
> 'missing t9n' means the program can not find language file under \common\text\steam.
> You can get all language file extract from \chunk\chunk0.bin

Just extract everything under \common in \chunk\chunk0.bin.
