### ISSUE TITLE
ON 1.5.0 missing t9n

### ISSUE THREAD

**Issue by ssks9x** [fre-sch/mhw_armor_edit#7]
came from 1.2. updated all chunk files on merge (actually created new). Copied the armor.am_dat to different folder. when i open that file in editor mod directory (single armor.am_dat file on another folder) names are missing t9n. But when i open the file on the chunk directory itself i could see the name. wasnt like this on 1.2. Thanks

**Comment by fre-sch** [comment]
I cannot provide fixes for old versions. Use newer versions.
