### ISSUE TITLE
1-6-0 launches an error when opening .wp_dat_g

### ISSUE THREAD

**Issue by MHWBuilder** [fre-sch/mhw_armor_edit#9]
1-5-0 seems fine.

**Comment by fre-sch** [comment]
Things that help fixing bugs:
* make sure to use merged chunks
* make sure to use a mod directory
* place the file in the mod directory
* do not mix/match with other modded files
* provide screenshots
  * show chunk directory and opened file selected
  * show mod directory and open file selected
  * use dropbox/google drive or any other simple file hoster to provide the file causing issues
